[project]
name = "se3-electricity-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hossain007Bhuiyan", email = "hossain.se@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "captum>=0.9.0",
    "holidays>=0.105",
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
]

[project.scripts]
se3-electricity-forecast = "se3_electricity_forecast:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
